"""
api/demo.py — Demo control + glove command endpoints
GET  /api/demo/status
POST /api/demo/trigger
GET  /api/demo/scenarios   ← used by DemoPanel UI (dynamic, no hardcoded values)
GET  /api/glove/command    ← polled by ESP32 every 3s for wireless scenario sync
"""
import time, json
from flask import Blueprint, request, jsonify, current_app, Response
from simulation.engine import list_scenarios, get_metadata, build as sim_build
from api import vitals as vitals_module

bp = Blueprint("demo", __name__)


@bp.route("/api/demo/status", methods=["GET"])
def demo_status():
    esp32_ts = current_app.config.get("LAST_ESP32_TS", 0)
    scenario = current_app.config.get("ACTIVE_SCENARIO")
    return jsonify({
        "scenario":      scenario,
        "dataSource":    current_app.config.get("DATA_SOURCE", "simulation"),
        "esp32Connected": (time.time() * 1000 - esp32_ts) < 6000 and esp32_ts > 0,
        "scenarioMeta":  get_metadata(scenario) if scenario else get_metadata("normal"),
    })


@bp.route("/api/demo/trigger", methods=["POST"])
def demo_trigger():
    body   = request.get_json(silent=True) or {}
    scene  = body.get("scene")
    source = body.get("source")

    if scene is not None:
        sid = None if scene == "normal" else scene
        current_app.config["ACTIVE_SCENARIO"]       = sid
        vitals_module._sim_scenario                 = sid
        vitals_module._scenario_start_tick          = vitals_module._sim_tick

    if source in ("device", "simulation"):
        current_app.config["DATA_SOURCE"] = source

    active = current_app.config.get("ACTIVE_SCENARIO")
    return jsonify({
        "ok":          True,
        "scenario":    active,
        "dataSource":  current_app.config.get("DATA_SOURCE", "simulation"),
        "meta":        get_metadata(active) if active else get_metadata("normal"),
    })


@bp.route("/api/demo/scenarios", methods=["GET"])
def get_scenarios():
    """Return all 9 registered scenario metadata objects — used by DemoPanel UI."""
    return jsonify(list_scenarios())


@bp.route("/api/glove/command", methods=["GET"])
def glove_command():
    """
    Polled by the ESP32 every 3 seconds.
    Returns the active scenario so the OLED can display it wirelessly.
    Uses the SAME simulated vitals that /api/latest generated, ensuring
    the glove OLED and the web dashboard always show identical numbers.
    """
    scenario = current_app.config.get("ACTIVE_SCENARIO") or "normal"
    meta     = get_metadata(scenario) or {}

    # Use the shared reading generated by /api/latest so both systems
    # display exactly the same values.  Fall back to a fresh sim_build()
    # only if /api/latest hasn't been polled yet.
    sim = current_app.config.get("LATEST_SIM_READING")
    if sim is None:
        tick = vitals_module._sim_tick
        age  = tick - vitals_module._scenario_start_tick
        sim  = sim_build(tick, scenario if scenario != "normal" else None, age_ticks=age)

    # override=true tells the ESP32 to replace real sensor readings
    override = scenario != "normal"

    # MUST use compact JSON (no spaces after colons) because the ESP32's
    # minimal C++ parser does indexOf('"key":') — a space breaks it.
    payload = json.dumps({
        "scenario":    scenario,
        "label":       meta.get("label", "Normal Monitoring"),
        "description": meta.get("description", "Baseline vitals"),
        "risk_range":  meta.get("expected_risk_range", [5, 20]),
        "tier":        meta.get("expected_escalation_tier", 0),
        "gaps":        meta.get("gaps", []),
        "override":    1 if override else 0,
        "hr":          sim["hr"],
        "spo2":        sim["spo2"],
        "temp":        round(sim["temp"], 1),
        "gforce":      int(round(sim["gforce"] * 100)),
        "fall":        1 if sim["fall"] else 0,
    }, separators=(',', ':'))
    return Response(payload, mimetype='application/json')

